"""added updated at in Chat model

Revision ID: f8528c1a48c7
Revises: 57dd2a457937
Create Date: 2026-03-29 10:16:24.348488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8528c1a48c7'
down_revision: Union[str, Sequence[str], None] = '57dd2a457937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    
    op.execute(
        "UPDATE chat SET updated_at = created_at WHERE updated_at IS NULL"
    )
    
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.alter_column('updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'updated_at')
    # ### end Alembic commands ###
